CREATE TABLE IF NOT EXISTS parcels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident VARCHAR(140) NOT NULL,
    building CHAR(1) NOT NULL CHECK (building IN ('A', 'B', 'C')),
    apartment VARCHAR(12) NOT NULL,
    carrier VARCHAR(100) NOT NULL DEFAULT 'Não informado',
    porter VARCHAR(140) NOT NULL,
    notes TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'picked_up')),
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    picked_up_at TIMESTAMPTZ,
    CHECK ((status = 'pending' AND picked_up_at IS NULL) OR (status = 'picked_up' AND picked_up_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS parcels_received_at_idx ON parcels (received_at DESC);
CREATE INDEX IF NOT EXISTS parcels_status_idx ON parcels (status);
CREATE INDEX IF NOT EXISTS parcels_resident_idx ON parcels (resident);